Repository andela/ah-the-phoenix-frontend, pull requests merged in 2019-03, with the labels that each got.

#6 #163388089 Set up redux
  package.json
  src/index.js
  src/redux/actioncreators/index.js
  src/redux/actiontypes.js
  src/redux/reducers/index.js
  src/redux/store.js
Labels: FTL review needed

#5 #163388093 Setup SASS pre-processing
  package.json
  src/index.js
  src/index.scss
Labels: FTL review needed

#7 #163388092 Setup react-router
  package.json
  src/App.js
  src/views/index.js
Labels: FTL review needed

#11 #164593780 Host react-app on Heroku
  package.json
Labels: FTL review needed

#8 #163388095 User should be able to signup
  package.json
  public/index.html
  src/App.js
  src/components/AuthForm/AuthForm.js
  src/components/AuthForm/AuthForm.scss
  src/components/Home/Home.js
  src/components/Home/Home.scss
  src/components/Loader/Loader.js
  src/components/Loader/Loader.scss
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/index.js
  src/index.scss
  src/redux/actioncreators/VerifyMail.js
  src/redux/actioncreators/loginActions.js
  src/redux/actioncreators/signupActions.js
  src/redux/actiontypes.js
  src/redux/reducers/VerifyMail.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/signupReducer.js
  src/redux/store.js
  src/utils/axios_config.js
  src/views/Signup/Signup.js
  src/views/Signup/Signup.scss
  src/views/SocialAuth/SocialAuth.js
  src/views/VerifyMail/VerifyMail.js
  src/views/VerifyMail/VerifyMail.scss
  src/views/index.js
Labels: wip

#10 #163388097 User should be able to login
  .gitignore
  public/index.html
  src/App.js
  src/components/AuthForm/AuthForm.js
  src/components/AuthForm/AuthForm.scss
  src/components/NavBar/NavBar.js
  src/redux/actioncreators/index.js
  src/redux/actioncreators/loginActions.js
  src/redux/actiontypes.js
  src/redux/reducers/loginReducer.js
  src/views/Login/Login.js
  src/views/Login/Login.scss
  src/views/SocialAuth/SocialAuth.js
Labels: Devs review needed

#12 #163388096 A user should be able to reset their password
  public/index.html
  src/App.js
  src/App.test.js
  src/components/AuthForm/AuthForm.js
  src/components/Home/Home.js
  src/components/NavBar/NavBar.js
  src/components/passwordReset/ResetForm.js
  src/components/passwordReset/UpdateForm.js
  src/index.js
  src/index.scss
  src/redux/actioncreators/passwordResetActions.js
  src/redux/actioncreators/passwordUpdateActions.js
  src/redux/actiontypes.js
  src/redux/reducers/index.js
  src/redux/reducers/pwdUpdateReducer.js
  src/redux/reducers/resetReducer.js
  src/redux/store.js
  src/setupTests.js
  src/utils/axios_config.js
  src/views/PasswordReset/PasswordReset.js
  src/views/PasswordReset/PasswordReset.scss
  src/views/PasswordReset/PasswordUpdate.js
  src/views/Signup/Signup.js
Labels: Devs review needed

#9 #163388099 Get and Display User Profile
  package.json
  src/App.js
  src/components/NavBar/NavBar.js
  src/components/Profile/EditProfileForm.js
  src/components/Profile/ProfileCard.js
  src/components/Profile/profile.scss
  src/helpers/uploader.js
  src/index.js
  src/redux/actioncreators/editProfile.js
  src/redux/actioncreators/userProfile.js
  src/redux/actiontypes.js
  src/redux/reducers/index.js
  src/redux/reducers/profileReducer.js
  src/redux/store.js
  src/views/SocialAuth/SocialAuth.js
  src/views/editProfile.js
  src/views/getProfile.js
Labels: Devs review needed

#24 #163388100 Get Articles Feature
  package.json
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/ListArticles.js
  src/components/Profile/ProfileCard.js
  src/redux/actioncreators/getArticleActions.js
  src/redux/actioncreators/listArticlesActions.js
  src/redux/actiontypes.js
  src/redux/reducers/getArticleReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/listArticlesReducer.js
Labels: Devs review needed, FTL review needed

#22 #163388100 Enable a user to create an article
  package.json
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/ListArticles.js
  src/components/AuthForm/AuthForm.js
  src/components/CreateEditArticle/CreateEditArticle.js
  src/components/CreateEditArticle/CreateEditArticle.scss
  src/components/NavBar/NavBar.js
  src/helpers/SignupValidate.js
  src/helpers/validator.js
  src/redux/actioncreators/__tests__/CreateArticle.test.js
  src/redux/actioncreators/createArticle.js
  src/redux/actioncreators/getArticleActions.js
  src/redux/actioncreators/listArticlesActions.js
  src/redux/actiontypes.js
  src/redux/reducers/__tests__/CreateArticle.test.js
  src/redux/reducers/createArticle.js
  src/redux/reducers/index.js
  src/views/AddArticle/AddArticle.js
Labels: Devs review needed, FTL review needed

#23 #163388100 Add delete article feature
  package.json
  src/components/Articles/Article.js
  src/components/Articles/ListArticles.js
  src/components/AuthForm/AuthForm.js
  src/components/CreateEditArticle/CreateEditArticle.js
  src/components/NavBar/NavBar.js
  src/components/Profile/EditProfileForm.js
  src/redux/actioncreators/__tests__/deleteArticle.test.js
  src/redux/actioncreators/__tests__/loginActions.test.js
  src/redux/actioncreators/createArticle.js
  src/redux/actioncreators/deleteArticle.js
  src/redux/actioncreators/editProfile.js
  src/redux/actioncreators/loginActions.js
  src/redux/actioncreators/userProfile.js
  src/redux/actiontypes.js
  src/redux/reducers/__tests__/articleReducer.test.js
  src/redux/reducers/__tests__/loginReducer.test.js
  src/redux/reducers/__tests__/profileReducer.test.js
  src/redux/reducers/articlesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/utils/axios_config.js
  src/views/Login/Login.js
Labels: Devs review needed, FTL review needed

#21 #163388100 Author should be able to edit their articles
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/Article.scss
  src/components/Articles/ArticlesContainer.js
  src/components/Articles/ListArticles.js
  src/components/CreateEditArticle/CreateEditArticle.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/index.scss
  src/redux/actioncreators/__tests__/loginActions.test.js
  src/redux/actioncreators/loginActions.js
  src/redux/actioncreators/updateArticle.js
  src/redux/actiontypes.js
  src/redux/reducers/articlesReducer.js
  src/redux/reducers/index.js
  src/utils/axios_config.js
  src/views/AddArticle/AddArticle.js
  src/views/EditArticle/EditArticle.js
  src/views/Login/Login.js
Labels: Devs review needed, FTL review needed

#26 #164765979 User should see their articles on their profile
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/ArticlesContainer.js
  src/components/Articles/ListArticles.js
  src/components/CreateEditArticle/CreateEditArticle.js
  src/components/Home/Home.js
  src/components/Profile/ProfileCard.js
  src/components/Profile/ProfileMenu.js
  src/components/Profile/UserArticles.js
  src/redux/reducers/__tests__/CreateArticle.test.js
  src/redux/reducers/__tests__/articleReducer.test.js
  src/redux/reducers/articlesReducer.js
  src/redux/reducers/createArticle.js
  src/redux/reducers/getArticleReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/listArticlesReducer.js
  src/views/Profile/editProfile.js
  src/views/Profile/getProfile.js
Labels: Devs review needed, FTL review needed

#28 #163388101 User should be able to rate an article
  src/App.js
  src/components/Articles/Article.js
  src/components/Profile/ProfileMenu.js
  src/redux/actioncreators/getRatingActions.js
  src/redux/actioncreators/postRatingActions.js
  src/redux/actiontypes.js
  src/redux/reducers/index.js
  src/redux/reducers/ratingsReducer.js
Labels: Devs review needed, FTL review needed

#30 #163388104 Enable a user to like and dislike an article
  package.json
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/LikeDislike.js
  src/redux/actioncreators/__tests__/LikeDislike.test.js
  src/redux/actioncreators/getRatingActions.js
  src/redux/actioncreators/likeDislikeArticle.js
  src/redux/actioncreators/loginActions.js
  src/redux/actiontypes.js
  src/redux/reducers/LikeDislike.js
  src/redux/reducers/__tests__/LikeDislike.test.js
  src/redux/reducers/articlesReducer.js
  src/redux/reducers/index.js
  src/redux/store.js
Labels: Devs review needed, FTL review needed

#29 #163388100 Add tests for update article reducer and actions
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/ArticlesContainer.js
  src/components/CreateEditArticle/CreateEditArticle.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
  src/components/Profile/ProfileCard.js
  src/components/Profile/profile.scss
  src/images/background.jpg
  src/index.scss
  src/redux/actioncreators/__tests__/updateArticle.test.js
  src/redux/actioncreators/updateArticle.js
  src/redux/reducers/__tests__/updateArticle.test.js
  src/redux/reducers/articlesReducer.js
  src/views/Login/Login.js
  src/views/Signup/Signup.js
Labels: Devs review needed, FTL review needed

#34 #163388107 Authenticated users should be able to follow/unfollow others
  src/App.js
  src/components/Articles/Article.js
  src/components/Articles/ArticlesContainer.js
  src/components/NavBar/NavBar.js
  src/components/Profile/EditProfileForm.js
  src/components/Profile/FollowersFollowing.js
  src/components/Profile/ProfileCard.js
  src/components/Profile/ProfileMenu.js
  src/redux/actioncreators/editProfile.js
  src/redux/actioncreators/followingActions.js
  src/redux/actioncreators/userProfile.js
  src/redux/actiontypes.js
  src/redux/reducers/profileReducer.js
  src/views/Profile/editProfile.js
  src/views/Profile/getProfile.js
Labels: Devs review needed, FTL review needed

#33 #163388106 Enable a user to share an article
  package.json
  src/components/Articles/Article.js
  src/components/Articles/Article.scss
  src/components/SocialShare/SocialShare.js
  src/components/SocialShare/SocialShare.scss
  src/index.scss
Labels: Devs review needed, FTL review needed

#31 #163388112 users can bookmark articles
  src/components/Articles/Article.js
  src/components/Articles/ArticlesContainer.js
  src/components/NavBar/NavBar.scss
  src/components/Profile/ListBookmarkedArticles.js
  src/components/Profile/ProfileMenu.js
  src/redux/actioncreators/bookmarkArticleActions.js
  src/redux/actioncreators/listArticlesActions.js
  src/redux/actioncreators/listBookmarkedArticles.js
  src/redux/actioncreators/unBookmarkArticleActions.js
  src/redux/actiontypes.js
  src/redux/reducers/bookmarkArticleReducer.js
  src/redux/reducers/index.js
Labels: Devs review needed, FTL review needed

#35 #163388109 Users can opt in or out of notifications
  src/App.js
  src/components/Articles/Article.js
  src/components/Home/Subscribe.js
  src/components/Profile/FollowersFollowing.js
  src/components/Profile/ListBookmarkedArticles.js
  src/components/Profile/ProfileMenu.js
  src/components/Profile/Subscribe.js
  src/redux/actioncreators/getRatingActions.js
  src/redux/actioncreators/subscribeActions.js
  src/redux/actioncreators/unsubscribeActions.js
  src/redux/actiontypes.js
  src/redux/reducers/profileReducer.js
  src/redux/reducers/ratingsReducer.js
  src/redux/reducers/subscriptionReducer.js
  src/views/Profile/getProfile.js
Labels: Devs review needed, FTL review needed
